apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: amittomcat 
spec:
  replicas: 2 
  selector:
   matchLabels:
    app: amittomcat 
  template:
    metadata: 
      labels:
        app: amittomcat
    spec:
      containers:
      - name: amittomcat
        image: amitkrbeck/sp6k8s:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: amittomcat-svc 
  labels:
    app: amittomcat 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080 
  selector:
    app: amittomcat
